# shellcheck shell=bash
# Config files are generated from templates/ for the set of installed modules,
# so adding or undoing a module always leaves configs consistent.

TPL="$DEVENV_HOME/templates"
NVIM_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
TMUX_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tmux"
DEVENV_CFG="${XDG_CONFIG_HOME:-$HOME/.config}/devenv"

scratch() { mktemp "${TMPDIR:-/tmp}/devenv.XXXXXX"; }

# Replace the line holding @@KEY@@ with the contents of <content-file>.
subst_line() {
  local f=$1 key=$2 content=$3 tmp
  tmp=$(scratch)
  awk -v k="@@$key@@" -v c="$content" 'index($0, k) { while ((getline l < c) > 0) print l; next } { print }' "$f" >"$tmp"
  mv "$tmp" "$f"
}

# Replace @@KEY@@ placeholders: subst <file> KEY value [KEY value...]
subst() {
  local f=$1 tmp; shift
  while [ $# -ge 2 ]; do
    tmp=$(scratch)
    awk -v k="@@$1@@" -v v="$2" '{ while ((i = index($0, k)) > 0) $0 = substr($0, 1, i - 1) v substr($0, i + length(k)); print }' "$f" >"$tmp"
    mv "$tmp" "$f"
    shift 2
  done
}

# Write a file only the first time (user-owned afterwards).
install_once() {
  local module=$1 src=$2 dest=$3
  if [ -n "$(find_record file "$dest")" ]; then return 0; fi
  if [ -e "$dest" ]; then
    # In a dry run, files inside a directory that would be moved aside count as new.
    case "${DRY_ADOPTED:-//}" in
      //) return 0 ;;
      *) case "$dest" in "$DRY_ADOPTED"/*) ;; *) return 0 ;; esac ;;
    esac
  fi
  install_file "$module" "$src" "$dest"
}

# Move a file that would shadow ours out of the way (e.g. ~/.tmux.conf is read
# before ~/.config/tmux/tmux.conf). Undo puts it back.
displace() {
  local module=$1 path=$2 b
  [ -e "$path" ] || [ -L "$path" ] || return 0
  [ -n "$(find_record replace "$path")" ] && return 0
  if is_dry; then step "would move $(tilde "$path") aside (it belongs to the replaced config)"; return 0; fi
  b=$(stash "$path")
  record "$module" replace "$path" "$b"
  warn "moved $(tilde "$path") to $(tilde "$b") (it would override devenv's config)"
}

render_nvim() {
  local mods=$1 m x f tmp extras='' replacing=0
  if [ -e "$NVIM_DIR" ] && [ -z "$(find_record dir "$NVIM_DIR")" ]; then replacing=1; fi
  adopt_dir nvim "$NVIM_DIR"
  # A previous config's plugins and caches belong to it: set them aside too.
  if [ "$replacing" = 1 ]; then
    for x in "$HOME/.local/share/nvim" "$HOME/.local/state/nvim" "$HOME/.cache/nvim"; do
      [ -n "$(find_record dir "$x")" ] || displace nvim "$x"
    done
  fi

  install_file nvim "$TPL/nvim/init.lua" "$NVIM_DIR/init.lua"
  install_file nvim "$TPL/nvim/lua/config/lazy.lua" "$NVIM_DIR/lua/config/lazy.lua"
  install_file nvim "$TPL/nvim/lua/devenv/options.lua" "$NVIM_DIR/lua/devenv/options.lua"
  install_file nvim "$TPL/nvim/lua/devenv/keymaps.lua" "$NVIM_DIR/lua/devenv/keymaps.lua"
  install_file nvim "$TPL/nvim/lua/devenv/plugins/core.lua" "$NVIM_DIR/lua/devenv/plugins/core.lua"
  for f in options keymaps autocmds; do
    install_once nvim "$TPL/nvim/lua/config/$f.lua" "$NVIM_DIR/lua/config/$f.lua"
  done
  install_once nvim "$TPL/nvim/lua/plugins/user.lua" "$NVIM_DIR/lua/plugins/user.lua"

  tmp=$(scratch)
  {
    echo "-- Generated by devenv from your installed modules. Do not edit:"
    echo "-- run \`devenv install <module>\` / \`devenv undo <module>\` instead,"
    echo "-- or enable more extras in lua/plugins/ (e.g. { import = \"lazyvim.plugins.extras.lang.ruby\" })."
    echo "return {"
    for m in $mods; do
      extras=$(mod_get "$m" extras)
      [ -n "$extras" ] || continue
      echo "  -- $m"
      for x in $extras; do
        echo "  { import = \"lazyvim.plugins.extras.$x\" },"
      done
    done
    echo "}"
  } >"$tmp"
  install_file nvim "$tmp" "$NVIM_DIR/lua/devenv/extras.lua"
  rm -f "$tmp"

  for m in $(all_modules); do
    f="$TPL/nvim/modules/$m.lua"
    [ -f "$f" ] || continue
    if word_in "$m" "$mods"; then
      install_file "$m" "$f" "$NVIM_DIR/lua/devenv/plugins/$m.lua"
    else
      remove_file_if_ours "$NVIM_DIR/lua/devenv/plugins/$m.lua"
    fi
  done
}

render_tmux() {
  local term=screen-256color tmp
  if has infocmp && infocmp tmux-256color >/dev/null 2>&1; then term=tmux-256color; fi
  displace tmux "$HOME/.tmux.conf"
  tmp=$(scratch)
  cp "$TPL/tmux/tmux.conf" "$tmp"
  subst "$tmp" TMUX_TERM "$term"
  install_file tmux "$tmp" "$TMUX_DIR/tmux.conf"
  rm -f "$tmp"
  install_file tmux "$TPL/tmux/tmux-sessionizer" "$HOME/.local/bin/tmux-sessionizer" 755
}

render_wezterm() {
  local dir tmp settings shell size=14 lines
  if [ "$IS_WSL" = 1 ]; then
    local wh
    wh=$(windows_home) || { warn "could not find your Windows home folder; skipping WezTerm config"; return 0; }
    dir="$wh/.config/wezterm"
    displace wezterm "$wh/.wezterm.lua"
    size=11
    shell=${SHELL:-/bin/bash}
    settings="local devenv = { shell = \"$shell\", font_size = $size, wsl_distro = \"${WSL_DISTRO_NAME:-Ubuntu}\" }"
  else
    dir="${XDG_CONFIG_HOME:-$HOME/.config}/wezterm"
    displace wezterm "$HOME/.wezterm.lua"
    [ "$OS" = linux ] && size=11
    shell=${SHELL:-/bin/zsh}
    settings="local devenv = { shell = \"$shell\", font_size = $size }"
  fi
  tmp=$(scratch) lines=$(scratch)
  printf -- '-- generated by devenv for %s\n%s\n' "$PLATFORM_LABEL" "$settings" >"$lines"
  cp "$TPL/wezterm/wezterm.lua" "$tmp"
  subst_line "$tmp" DEVENV_SETTINGS "$lines"
  install_file wezterm "$tmp" "$dir/wezterm.lua"
  rm -f "$tmp" "$lines"
}

render_shell() {
  local mods=$1 m tmp
  tmp=$(scratch)
  cat "$TPL/shell/base.sh" >"$tmp"
  for m in $mods; do
    [ -f "$TPL/shell/$m.sh" ] || continue
    printf '\n' >>"$tmp"
    cat "$TPL/shell/$m.sh" >>"$tmp"
  done
  cat "$TPL/shell/tail.sh" >>"$tmp"
  subst "$tmp" BREW "$BREW" BREW_PREFIX "$BREW_PREFIX"
  install_file shellrc "$tmp" "$DEVENV_CFG/shell.sh"
  rm -f "$tmp"
  put_block shellrc "$RC_FILE" "[ -f \"\$HOME/.config/devenv/shell.sh\" ] && . \"\$HOME/.config/devenv/shell.sh\""
}

# render_all "<modules>": write configs for the core modules in the set.
render_all() {
  local mods=$1
  phase "Writing configuration"
  word_in shellrc "$mods" && render_shell "$mods"
  word_in tmux "$mods" && render_tmux
  word_in nvim "$mods" && render_nvim "$mods"
  word_in wezterm "$mods" && render_wezterm
  return 0
}
