# Shell setup generated by devenv (works in zsh and bash). Regenerated on every
# `devenv install`; put your own additions in ~/.config/devenv/local.sh.

__devenv_path() { case ":$PATH:" in *":$1:"*) ;; *) [ -d "$1" ] && PATH="$1:$PATH" ;; esac; }
# Same, but at the end: fills gaps without shadowing anything already on PATH.
__devenv_path_append() { case ":$PATH:" in *":$1:"*) ;; *) [ -d "$1" ] && PATH="$PATH:$1" ;; esac; }

[ -x "@@BREW@@" ] && eval "$("@@BREW@@" shellenv)"
__devenv_path "$HOME/.local/bin"
export PATH

if [ -n "${ZSH_VERSION:-}" ]; then __devenv_sh=zsh; else __devenv_sh=bash; fi

export EDITOR=nvim VISUAL=nvim
export MANPAGER='nvim +Man!'
export HOMEBREW_NO_ENV_HINTS=1

# History: big, shared, deduplicated.
if [ "$__devenv_sh" = zsh ]; then
  HISTFILE=${HISTFILE:-$HOME/.zsh_history}
  HISTSIZE=100000 SAVEHIST=100000
  setopt share_history hist_ignore_all_dups hist_ignore_space hist_reduce_blanks extended_history
  setopt auto_cd interactive_comments
  autoload -Uz compinit && compinit -i
  zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'   # case-insensitive completion
  zstyle ':completion:*' menu select
  bindkey -e
else
  HISTSIZE=100000 HISTFILESIZE=100000
  HISTCONTROL=ignoreboth:erasedups
  shopt -s histappend checkwinsize 2>/dev/null
fi

alias vim=nvim vi=nvim v=nvim
alias lg=lazygit
alias tm='tmux new-session -A -s main'
alias ..='cd ..' ...='cd ../..'
if command -v eza >/dev/null 2>&1; then
  alias ls='eza --group-directories-first'
  alias ll='eza -lah --git --group-directories-first'
  alias lt='eza --tree --level=2 --git-ignore'
fi
command -v bat >/dev/null 2>&1 && export BAT_THEME=ansi

# Integrations: Ctrl-r / Ctrl-t / Alt-c fuzzy search, `z <dir>` jumping, prompt.
command -v fzf >/dev/null 2>&1 && eval "$(fzf --$__devenv_sh)"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git'
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
export FZF_DEFAULT_OPTS='--height 40% --layout reverse --border --color=bg+:#283457,fg+:#c0caf5,hl:#7aa2f7,hl+:#7dcfff,pointer:#ff9e64,prompt:#7aa2f7'
command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init $__devenv_sh)"
command -v starship >/dev/null 2>&1 && eval "$(starship init $__devenv_sh)"
